---
- hosts: 172.31.34.70
  become: yes
  tasks:
  - name: i want to execute linux command
    command: hostname -f
    register: myfirstresult

  - name: i want to display my task result
    debug:
       msg: "{{myfirstresult}}" 

  - name: i want to install git
    apt:
      name: git
      state: present
    when: myfirstresult.stderr ==""

  - name: i want to install tree
    apt:
      name: tree
      state: present
    when: myfirstresult.stderr !=""     